#!/bin/bash

module load intelcomp/14.0.1
module load mpt/2.09
module load python/2.7.6

export MPI_INCLUDES='/sw/sgi/mpt/mpt-2.09/include/;/sw/sgi/mpt/mpt-2.09/include/mpp/;/sw/sgi/mpt/mpt-2.09/include/pgi/;/sw/sgi/mpt/mpt-2.09/lib/;/sw/sgi/mpt/mpt-2.09/'

rm -f src/*.html src/*.c
rm -f modules/*.pyc
rm -f *.so
rm -f *.pyc
rm -rf build
/sw/sdev/Modules/python/python-2.7.6/bin/python setup.py build_ext --inplace

